export const LEGAL_EFFECTIVE_DATE = "July 11, 2026";
export const SUPPORT_EMAIL = "support@astroyou.com";

// TODO(legal): confirm the Grievance Officer named below (DPDP Act §13 requires
// a reachable grievance contact) and have counsel review the Privacy Policy
// sections before launch — the processor list, retention periods, and transfer
// disclosures were drafted by engineering and are not a substitute for review.
export const GRIEVANCE_OFFICER = {
  name: "[Grievance Officer name]",
  email: "grievance@astroyou.com",
};

export interface LegalSection {
  title: string;
  content: string[];
}

export const TERMS_SECTIONS: LegalSection[] = [
  {
    title: "1. Service",
    content: [
      "AstroYou provides Vedic astrology tools, chart calculations, AI-generated interpretations, AI astrologer consultations, reports, reminders, and spiritual companion features.",
      "The platform is for reflection, education, entertainment, and spiritual guidance. It is not a substitute for professional medical, legal, financial, psychological, or emergency advice.",
    ],
  },
  {
    title: "2. Accounts and Birth Data",
    content: [
      "You are responsible for keeping your account secure and for providing accurate birth details if you want accurate chart calculations.",
      "Some features require date, time, place of birth, current location, language, profile data, chat history, and saved guidance context.",
    ],
  },
  {
    title: "3. AI-Generated Guidance",
    content: [
      "AI astrologer sessions and AI Jyotish responses are generated by artificial intelligence. They can be useful, but may be incomplete, incorrect, or unsuitable for your situation.",
      "Do not treat predictions as guaranteed outcomes. Important health, legal, financial, safety, or relationship decisions should be discussed with qualified professionals.",
    ],
  },
  {
    title: "4. Credits, Plans, and Payments",
    content: [
      "AstroYou uses credits for paid sessions, reports, and other paid features. Credit cost is shown before use.",
      "Purchased credits are not cash, cannot be resold, and are tied to your AstroYou account.",
      "Subscriptions renew through Razorpay unless cancelled. Plan benefits, monthly credits, and usage limits are shown on the Pricing page.",
    ],
  },
  {
    title: "5. Refunds",
    content: [
      "Refund requests are handled under the Refund Policy. Failed payments, duplicate charges, and unused-credit cases can be reviewed through Support.",
      "Consumed credits are normally not refundable because the consultation, report, or paid feature has already been delivered.",
    ],
  },
  {
    title: "6. Acceptable Use",
    content: [
      "You must not misuse the service, scrape or reverse-engineer the platform, bypass billing, overload systems, submit harmful content, or use AstroYou for unlawful activity.",
      "We may restrict or suspend accounts that abuse support, payment flows, AI systems, or other users.",
    ],
  },
  {
    title: "7. Intellectual Property",
    content: [
      "AstroYou's product design, code, content, prompts, models, branding, and generated platform experiences belong to AstroYou or its licensors.",
      "Your personal profile, birth data, chats, support requests, and wallet records remain your account data and are handled under the Privacy Policy.",
    ],
  },
  {
    title: "8. Liability",
    content: [
      "AstroYou is provided on an as-is and as-available basis. We do not promise uninterrupted access, perfect predictions, or error-free output.",
      "To the maximum extent allowed by law, our liability for claims related to the service is limited to the amount you paid to AstroYou in the 12 months before the claim.",
    ],
  },
  {
    title: "9. Changes and Contact",
    content: [
      "We may update these terms. Material changes may be communicated by in-app notice or email.",
      `Questions about these terms can be sent to ${SUPPORT_EMAIL}.`,
    ],
  },
];

export const PRIVACY_SECTIONS: LegalSection[] = [
  {
    title: "1. Data We Collect",
    content: [
      "Account data: email, display name, authentication identifiers, language, and support contact details.",
      "Astrology data: date, time, place of birth, coordinates, current location when provided, chart calculations, compatibility inputs, reports, and forecast context.",
      "Usage data: pages visited, feature actions, wallet activity, purchases, subscriptions, referrals, install events, and support tickets.",
      "Guidance data: chat messages, consultation summaries, saved Atman memory, routines, emotional state, relationships, prediction feedback, and testimonial/review submissions.",
    ],
  },
  {
    title: "2. How We Use Data",
    content: [
      "We use data to create charts, personalize guidance, remember context, operate credits and payments, generate reports, provide support, prevent abuse, improve the product, and comply with legal or operational obligations.",
      "We do not sell your personal data.",
    ],
  },
  {
    title: "3. Service Providers We Share Data With",
    content: [
      "We use the following processors to run AstroYou, and share only the data each needs for its function:",
      "Google (Firebase Authentication, Firestore, Cloud Storage, Cloud Functions/Netlify hosting): stores your account, profile, birth data, chats, and product records, and handles sign-in.",
      "astrology-api.io (chart calculation): receives the birth date, time, and place/coordinates needed to compute charts, dashas, and timings. It does not need and should not receive your real name.",
      "Google Gemini (AI generation): receives the prompt, chart context, relevant chat content, and saved guidance memory needed to generate a response.",
      "Razorpay (payments and subscriptions): processes your payment. AstroYou never stores full card numbers, CVV, UPI PIN, OTPs, or net-banking passwords.",
      "Resend (email delivery): receives your email address and the content of transactional and digest emails you have enabled.",
      "Google Analytics / Firebase Analytics (usage measurement): receives product usage events. It is loaded only after you accept the privacy notice at sign-in; anonymous visitors are not tracked.",
    ],
  },
  {
    title: "4. International Transfers",
    content: [
      "Some of these providers process data on servers outside India (for example in the United States or European Union). Where data is transferred across borders, we rely on the provider's contractual and technical safeguards and process it consistent with applicable law.",
    ],
  },
  {
    title: "5. Sensitive Data",
    content: [
      "Guidance features store emotional-state notes, relationship context, and reflections you choose to share. This may be treated as sensitive or special-category personal data under laws such as the GDPR. We use it only to personalize your guidance and remember context, and you can remove it through Support.",
    ],
  },
  {
    title: "6. How Long We Keep Data",
    content: [
      "Account, profile, birth data, and saved guidance: kept while your account is active, and deleted or anonymized within 30 days of an account-deletion request, except records we must retain longer.",
      "Payment, invoice, and credit-ledger records: retained for up to 8 years to meet tax, accounting, and fraud-prevention obligations.",
      "One-time login codes: deleted or expired within minutes. Rate-limit and short-lived cache records expire automatically, typically within a day.",
      "Analytics and email-engagement events: retained in aggregated or limited form for product measurement and then rotated.",
    ],
  },
  {
    title: "7. Storage and Security",
    content: [
      "AstroYou stores account and product data in Firebase/Firestore and related cloud services. Access is account-bound and server operations use privileged backend credentials.",
      "No system is risk-free. If we discover a serious security issue affecting your data, we will take reasonable steps to investigate, contain, and notify affected users and authorities where required.",
    ],
  },
  {
    title: "8. Your Rights",
    content: [
      "You can export supported account data from Settings.",
      "You can request access to, correction of, or deletion of your account and eligible saved guidance data through Support. Some records may be retained where needed for payments, fraud prevention, legal obligations, dispute handling, or accounting.",
      "You can withdraw analytics consent by signing out, which stops analytics on this browser.",
      "You can opt out of optional notifications where the app provides that control.",
    ],
  },
  {
    title: "9. Children",
    content: [
      "AstroYou is not intended for children under 18. In line with India's Digital Personal Data Protection Act, we do not knowingly process the personal data of a child (a person under 18) without verifiable parental or guardian consent. If you believe a child has provided personal data, contact the Grievance Officer or Support so we can review and delete it.",
    ],
  },
  {
    title: "10. Grievance Officer and Contact",
    content: [
      `In accordance with applicable data-protection law, you may contact our Grievance Officer, ${GRIEVANCE_OFFICER.name}, at ${GRIEVANCE_OFFICER.email} for privacy concerns, access, correction, or deletion requests. We aim to acknowledge grievances within the timelines required by law.`,
      `General privacy questions, export issues, and deletion requests can also be sent to ${SUPPORT_EMAIL}.`,
    ],
  },
];

export const REFUND_SECTIONS: LegalSection[] = [
  {
    title: "1. What Can Be Reviewed",
    content: [
      "Failed payments where credits or plan access were not delivered.",
      "Duplicate charges for the same intended purchase.",
      "Unused purchased credits where no paid feature has been consumed from that purchase.",
      "Report generation failures where credits were charged but no usable report was delivered.",
      "Consultation billing issues where the server ledger does not match the delivered session.",
    ],
  },
  {
    title: "2. What Is Normally Not Refundable",
    content: [
      "Consumed credits after a consultation, report, AI chat, or paid feature has been delivered.",
      "Dissatisfaction with an astrological interpretation or prediction outcome.",
      "Subscription periods after plan credits or paid benefits have already been used.",
      "Loss caused by decisions made from astrology or AI-generated guidance.",
    ],
  },
  {
    title: "3. How To Request A Refund Review",
    content: [
      "Open Support, choose Refund Review, and include the payment ID, order ID, report ID, consultation ID, amount, date, and a short explanation.",
      "We may ask for account verification or screenshots that do not include sensitive payment credentials.",
      "Never share CVV, OTP, card PIN, UPI PIN, net-banking password, or full card details.",
    ],
  },
  {
    title: "4. Processing",
    content: [
      "Approved refunds are sent back to the original payment method through Razorpay where supported.",
      "Normal refunds may take 5-10 business days after processing, depending on the bank or payment method.",
      "Partial refunds may be used when only part of a payment is eligible.",
    ],
  },
  {
    title: "5. Support Target",
    content: [
      "We aim to acknowledge refund review tickets within 2 business days. Complex payment-provider or bank cases can take longer.",
      `For payment and refund issues, use Support or email ${SUPPORT_EMAIL}.`,
    ],
  },
];

export const DISCLAIMER_SECTIONS: LegalSection[] = [
  {
    title: "Astrology Is Guidance, Not Certainty",
    content: [
      "AstroYou provides astrology-based interpretations, timing windows, remedies, and AI-generated reflections. These outputs are not guarantees of future events.",
    ],
  },
  {
    title: "No Professional Advice",
    content: [
      "AstroYou does not provide medical, legal, financial, psychological, emergency, or professional decision-making advice.",
      "For health, safety, legal, financial, mental health, or crisis situations, contact qualified professionals or emergency services.",
    ],
  },
  {
    title: "AI Limitations",
    content: [
      "AI responses can be wrong, incomplete, repetitive, or overconfident. We use policy prompts and feedback systems to reduce this, but we cannot guarantee every answer.",
    ],
  },
  {
    title: "Remedies and Rituals",
    content: [
      "Any mantra, routine, puja, gemstone, fast, or ritual suggestion is optional spiritual guidance. Do not spend money, stop treatment, or make major decisions only because a remedy was suggested.",
    ],
  },
];
