import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";

const sections = [
  {
    title: "1. Service Description",
    content: `AstroYou is an AI-powered Vedic astrology platform that provides personalized astrological insights, birth chart analysis, transit predictions, and spiritual guidance. Our service combines traditional Vedic astrology calculations with artificial intelligence to deliver a modern spiritual companion experience.`,
  },
  {
    title: "2. Disclaimer",
    content: `AstroYou is provided for entertainment, educational, and spiritual guidance purposes only. Our services do not constitute professional medical, legal, financial, or psychological advice. Astrological insights should not be used as the sole basis for making important life decisions. Always consult qualified professionals for matters relating to health, law, or finances.`,
  },
  {
    title: "3. Account Responsibility",
    content: `You are responsible for maintaining the confidentiality of your account credentials. You agree to provide accurate birth data for astrological calculations. You are responsible for all activity that occurs under your account. Notify us immediately at support@astroyou.com if you suspect unauthorized access.`,
  },
  {
    title: "4. Credits and Payments",
    content: `AstroYou operates on a credit-based system. Credits are purchased through Razorpay and are non-refundable once consumed. Unused credits do not expire. Subscription plans auto-renew unless cancelled before the renewal date. Refund requests for subscriptions may be made within 7 days of purchase if no credits have been consumed during that period.`,
  },
  {
    title: "5. AI-Generated Content",
    content: `Content generated by our AI systems (including daily predictions, compatibility analyses, and chat responses) is produced by artificial intelligence and may not always be accurate. AI-generated astrological interpretations represent one possible reading of celestial data and should not be treated as absolute truth. We continuously improve our AI models but cannot guarantee the accuracy of any specific prediction or analysis.`,
  },
  {
    title: "6. Acceptable Use",
    content: `You agree not to:

- Use the service for any unlawful purpose.
- Attempt to reverse-engineer, decompile, or extract our AI models or algorithms.
- Share your account credentials with others.
- Use automated scripts or bots to access the service.
- Harass, abuse, or harm other users through our platform.
- Upload malicious content or attempt to compromise our systems.`,
  },
  {
    title: "7. Intellectual Property",
    content: `All content, designs, algorithms, AI models, and branding on AstroYou are the intellectual property of AstroYou and its licensors. Your birth chart data and chat history remain your personal data (see Privacy Policy). You may not reproduce, distribute, or create derivative works from our platform without written permission.`,
  },
  {
    title: "8. Limitation of Liability",
    content: `AstroYou is provided "as is" without warranties of any kind, express or implied. We are not liable for any decisions made based on astrological content provided through our platform. Our total liability to you for any claim arising from use of the service shall not exceed the amount you paid to us in the preceding 12 months.`,
  },
  {
    title: "9. Termination",
    content: `We reserve the right to suspend or terminate your account if you violate these Terms of Service. You may delete your account at any time by contacting support@astroyou.com. Upon termination, your right to use the service ceases immediately. Data deletion follows the process outlined in our Privacy Policy.`,
  },
  {
    title: "10. Changes to These Terms",
    content: `We may modify these Terms of Service at any time. Material changes will be communicated via email or in-app notification. Continued use of AstroYou after changes constitutes acceptance of the updated terms.`,
  },
  {
    title: "11. Contact Us",
    content: `For questions about these Terms of Service, contact us at:

Email: support@astroyou.com`,
  },
];

export default function Terms() {
  return (
    <div className="min-h-screen bg-[#030308] text-white">
      <div className="container mx-auto px-6 py-16 max-w-3xl">
        <Link
          to="/"
          className="inline-flex items-center gap-2 text-white/40 hover:text-white/70 transition-colors mb-12 text-sm"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to Home
        </Link>

        <h1 className="font-display text-4xl tracking-wide mb-4">
          Terms of Service
        </h1>
        <p className="text-white/40 text-sm mb-16">
          Effective Date: April 11, 2026
        </p>

        <div className="space-y-12">
          {sections.map((section) => (
            <div key={section.title}>
              <h2 className="text-lg font-semibold text-gold mb-4">
                {section.title}
              </h2>
              <div className="text-white/60 text-sm leading-relaxed whitespace-pre-line">
                <div
                  dangerouslySetInnerHTML={{
                    __html: section.content
                      .replace(
                        /\*\*(.*?)\*\*/g,
                        '<strong class="text-white/80">$1</strong>',
                      )
                      .replace(/^- /gm, "&bull; "),
                  }}
                />
              </div>
            </div>
          ))}
        </div>

        <div className="mt-24 pt-8 border-t border-white/[0.05] text-white/30 text-xs">
          <p>&copy; 2026 AstroYou. All rights reserved.</p>
        </div>
      </div>
    </div>
  );
}
